class_name GyroBlocks
extends RefCounted

const COLOR_EVENT := Color(0.11, 0.55, 0.62)

const ACTION_SCHEMAS := {
	"Print": [["message", "field.message"]],
	"SetVariable": [["name", "field.var_name", "var"], ["value", "field.value"]],
	"AddToVariable": [["name", "field.var_name", "var"], ["amount", "field.amount"]],
	"EmitEvent": [["event", "field.event", "event"], ["payload", "field.payload"]],
	"MoveNode": [["node", "field.node", "obj"], ["mode", "field.mode"], ["x", "field.x"], ["y", "field.y"]],
	"SetNodeProperty": [["node", "field.node", "obj"], ["property", "field.property"], ["x", "field.x"], ["y", "field.y"], ["value", "field.value"]],
	"SetSize": [["node", "field.node", "obj"], ["w", "field.w"], ["h", "field.h"]],
	"SetText": [["node", "field.node", "obj"], ["text", "field.text"]],
	"PlayAnimation": [["node", "field.node", "obj"], ["animation", "field.animation"]],
	"Spawn": [["scene", "field.scene"], ["parent", "field.parent"], ["x", "field.x"], ["y", "field.y"], ["variable", "field.variable"]],
	"CreateObject": [["name", "field.name"], ["type", "field.type"], ["x", "field.x"], ["y", "field.y"], ["w", "field.w"], ["h", "field.h"], ["color", "field.color"], ["text", "field.text"], ["texture", "field.texture", "sprite"], ["font", "field.font"], ["variable", "field.variable"]],
	"DeleteObject": [["node", "field.node", "obj"]],
	"SetVelocity": [["node", "field.node", "obj"], ["x", "field.vel_x"], ["y", "field.vel_y"]],
	"AddVelocity": [["node", "field.node", "obj"], ["x", "field.imp_x"], ["y", "field.imp_y"]],
	"SetGravity": [["node", "field.node", "obj"], ["value", "field.gravity"]],
	"SetSolid": [["node", "field.node", "obj"], ["on", "field.solid"]],
	"PlaySound": [["sound", "field.sound", "sound"], ["volume", "field.volume"], ["loop", "field.loop"]],
	"StopSound": [["sound", "field.sound", "sound"]],
	"StartTimer": [["name", "field.timer_name"], ["wait", "field.wait"], ["one_shot", "field.one_shot"], ["repeat", "field.repeat"]],
	"StopTimer": [["name", "field.timer_name"]],
	"SetVisible": [["node", "field.node", "obj"], ["on", "field.on"]],
	"SetOpacity": [["node", "field.node", "obj"], ["value", "field.percent"]],
	"SetRotation": [["node", "field.node", "obj"], ["mode", "field.mode"], ["angle", "field.angle"]],
	"SetScale": [["node", "field.node", "obj"], ["percent", "field.percent"], ["x", "field.x"], ["y", "field.y"]],
	"ChangeLayer": [["node", "field.node", "obj"], ["dir", "field.dir"]],
	"SetFontSize": [["node", "field.node", "obj"], ["size", "field.size"]],
	"SetColor": [["node", "field.node", "obj"], ["color", "field.color"]],
	"SetTextAlign": [["node", "field.node", "obj"], ["align", "field.align"]],
	"SaveValue": [["key", "field.key"], ["value", "field.value"]],
	"LoadValue": [["key", "field.key"], ["variable", "field.variable", "var"]],
	"RandomSeed": [["seed", "field.seed"]],
	"Quit": [],
	"Toast": [["text", "field.text"]],
	"Wait": [["wait", "field.wait"]],
	"SetBackgroundColor": [["color", "field.color"]],
	"SetOrientation": [["mode", "field.mode"]],
	"Clipboard": [["mode", "field.mode"], ["text", "field.text"], ["variable", "field.variable", "var"]],
	"SetTexture": [["node", "field.node", "obj"], ["texture", "field.texture", "sprite"]],
	"SetCornerRadius": [["node", "field.node", "obj"], ["radius", "field.radius"]],
	"OpenURL": [["url", "field.url"]],
	"SetSoundVolume": [["sound", "field.sound", "sound"], ["volume", "field.volume"]],
	"SetSensor": [["node", "field.node", "obj"], ["on", "field.on"]],
	"SetPhysicsPaused": [["on", "field.on"]],
	"SetDraggable": [["node", "field.node", "obj"], ["on", "field.on"]],
	"FaceObject": [["node", "field.node", "obj"], ["target", "field.target", "obj"]],
	"SetPivot": [["node", "field.node", "obj"], ["x", "field.x"], ["y", "field.y"]],
	"SetObjectMeta": [["node", "field.node", "obj"], ["key", "field.key"], ["value", "field.value"]],
	"StopAnimation": [["node", "field.node", "obj"]],
	"SetCameraPosition": [["x", "field.x"], ["y", "field.y"]],
	"CameraFollow": [["node", "field.node", "obj"], ["smooth", "field.smooth"]],
	"TweenPosition": [["node", "field.node", "obj"], ["x", "field.x"], ["y", "field.y"], ["time", "field.time"], ["ease", "field.ease"]],
	"TweenScale": [["node", "field.node", "obj"], ["percent", "field.percent"], ["time", "field.time"], ["ease", "field.ease"]],
	"TweenRotation": [["node", "field.node", "obj"], ["angle", "field.angle"], ["time", "field.time"], ["ease", "field.ease"]],
	"TweenOpacity": [["node", "field.node", "obj"], ["value", "field.percent"], ["time", "field.time"], ["ease", "field.ease"]],
	"StopTween": [["node", "field.node", "obj"]],
	"ReadFile": [["path", "field.path"], ["variable", "field.variable", "var"]],
	"WriteFile": [["path", "field.path"], ["value", "field.value"]],
	"FileOp": [["op", "field.op"], ["path1", "field.path1"], ["path2", "field.path2"]],
	"HttpRequest": [["url", "field.url"], ["method", "field.method"], ["body", "field.body"], ["variable", "field.variable", "var"]],
	"CreateInput": [["name", "field.name"], ["text", "field.text"], ["multiline", "field.multiline"], ["secret", "field.secret"], ["x", "field.x"], ["y", "field.y"], ["w", "field.w"]],
	"CreateSlider": [["name", "field.name"], ["vertical", "field.vertical"], ["value", "field.value"], ["x", "field.x"], ["y", "field.y"]],
	"CreateToggle": [["name", "field.name"], ["on", "field.on"], ["x", "field.x"], ["y", "field.y"]],
	"GetWidgetText": [["widget", "field.widget", "obj"], ["variable", "field.variable", "var"]],
	"SetSliderValue": [["widget", "field.widget", "obj"], ["value", "field.value"]],
	"SetToggleState": [["widget", "field.widget", "obj"], ["on", "field.on"]],
	"AddTag": [["node", "field.node", "obj"], ["tag", "field.tag"]],
	"DeleteByTag": [["tag", "field.tag"]],
	"SetVisibleByTag": [["tag", "field.tag"], ["on", "field.on"]],
	"SetPositionByTag": [["tag", "field.tag"], ["mode", "field.mode"], ["x", "field.x"], ["y", "field.y"]],
	"SetRotationByTag": [["tag", "field.tag"], ["angle", "field.angle"]],
	"SetOpacityByTag": [["tag", "field.tag"], ["value", "field.percent"]],
	"SetScaleByTag": [["tag", "field.tag"], ["percent", "field.percent"]],
	"ChangeLayerByTag": [["tag", "field.tag"], ["dir", "field.dir"]],
	"If": [["condition", "field.condition"]],
	"Repeat": [["count", "field.count"]],
	"CreateGroup": [["name", "field.name"], ["x", "field.x"], ["y", "field.y"], ["w", "field.w"], ["h", "field.h"]],
	"AddToGroup": [["node", "field.node", "obj"], ["group", "field.group", "obj"]],
	"CreateSpriteAnim": [["name", "field.name"], ["sprite", "field.texture", "sprite"], ["frame_w", "field.frame_w"], ["frame_h", "field.frame_h"], ["count", "field.count"], ["fps", "field.fps"], ["anim", "field.anim"], ["x", "field.x"], ["y", "field.y"]],
	"SetFrame": [["node", "field.node", "obj"], ["frame", "field.frame"]],
	"CreateParticles": [["name", "field.name"], ["preset", "field.preset"], ["x", "field.x"], ["y", "field.y"]],
	"SetParticlesParam": [["node", "field.node", "obj"], ["param", "field.param"], ["value", "field.value"]],
	"DeleteParticles": [["node", "field.node", "obj"]],
	"SetGlobalGravity": [["value", "field.value"]],
	"CreateCircle": [["name", "field.name"], ["radius", "field.radius"], ["color", "field.color"], ["border_w", "field.border_w"], ["border_color", "field.border_color"], ["x", "field.x"], ["y", "field.y"]],
	"CreateLine": [["name", "field.name"], ["x", "field.x"], ["y", "field.y"], ["x2", "field.x2"], ["y2", "field.y2"], ["color", "field.color"], ["width", "field.width"]],
	"SetGradient": [["node", "field.node", "obj"], ["mode", "field.type"], ["color1", "field.color1"], ["color2", "field.color2"]],
	"SetBorder": [["node", "field.node", "obj"], ["color", "field.border_color"], ["width", "field.width"]],
	"SetParallax": [["node", "field.node", "obj"], ["x", "field.x"], ["y", "field.y"]],
	"SetTableValue": [["name", "field.table", "var"], ["key", "field.key"], ["value", "field.value"]],
	"GetTableValue": [["name", "field.table", "var"], ["key", "field.key"], ["variable", "field.variable", "var"]],
	"InsertArrayValue": [["name", "field.table", "var"], ["index", "field.index"], ["value", "field.value"]],
	"RemoveArrayValue": [["name", "field.table", "var"], ["index", "field.index"]],
	"OverwriteTable": [["name", "field.table", "var"], ["json", "field.json"]],
	"ForEachTable": [["name", "field.table", "var"], ["element", "field.element"], ["keyvar", "field.keyvar"]],
	"LoopRange": [["from", "field.from"], ["to", "field.to"], ["step", "field.step"], ["variable", "field.variable", "var"]],
	"SetAnchor": [["node", "field.node", "obj"], ["anchor", "field.anchor"]],
}

const CONDITION_SCHEMAS := {
	"Always": [],
	"VariableEquals": [["name", "field.var_name", "var"], ["value", "field.value"]],
	"VariableGreaterThan": [["name", "field.var_name", "var"], ["value", "field.value"]],
	"PayloadEquals": [["key", "field.key"], ["value", "field.value"]],
	"PayloadGreaterThan": [["key", "field.key"], ["value", "field.value"]],
}

const ACTION_COLORS := {
	"Print": Color(0.29, 0.56, 0.35),
	"SetVariable": Color(0.72, 0.55, 0.25),
	"AddToVariable": Color(0.65, 0.48, 0.20),
	"EmitEvent": Color(0.52, 0.35, 0.62),
	"MoveNode": Color(0.33, 0.58, 0.30),
	"SetNodeProperty": Color(0.33, 0.58, 0.30),
	"SetSize": Color(0.38, 0.62, 0.28),
	"SetText": Color(0.72, 0.55, 0.25),
	"PlayAnimation": Color(0.70, 0.33, 0.47),
	"Spawn": Color(0.78, 0.44, 0.18),
	"CreateObject": Color(0.38, 0.62, 0.28),
	"DeleteObject": Color(0.70, 0.25, 0.20),
	"SetVelocity": Color(0.18, 0.48, 0.70),
	"AddVelocity": Color(0.15, 0.60, 0.68),
	"SetGravity": Color(0.42, 0.32, 0.68),
	"SetSolid": Color(0.48, 0.48, 0.55),
	"PlaySound": Color(0.16, 0.55, 0.60),
	"StopSound": Color(0.55, 0.30, 0.30),
	"StartTimer": Color(0.20, 0.55, 0.50),
	"StopTimer": Color(0.55, 0.35, 0.30),
	"SetVisible": Color(0.38, 0.62, 0.28),
	"SetOpacity": Color(0.45, 0.55, 0.60),
	"SetRotation": Color(0.55, 0.45, 0.60),
	"SetScale": Color(0.50, 0.60, 0.30),
	"ChangeLayer": Color(0.40, 0.45, 0.62),
	"SetFontSize": Color(0.72, 0.55, 0.25),
	"SetColor": Color(0.70, 0.40, 0.45),
	"SetTextAlign": Color(0.65, 0.55, 0.30),
	"SaveValue": Color(0.35, 0.50, 0.55),
	"LoadValue": Color(0.30, 0.55, 0.50),
	"RandomSeed": Color(0.50, 0.50, 0.40),
	"Quit": Color(0.70, 0.25, 0.20),
	"Toast": Color(0.45, 0.50, 0.35),
	"Wait": Color(0.55, 0.50, 0.25),
	"SetBackgroundColor": Color(0.35, 0.40, 0.55),
	"SetOrientation": Color(0.40, 0.55, 0.45),
	"Clipboard": Color(0.50, 0.45, 0.50),
	"SetTexture": Color(0.45, 0.60, 0.50),
	"SetCornerRadius": Color(0.55, 0.55, 0.35),
	"OpenURL": Color(0.30, 0.45, 0.60),
	"SetSoundVolume": Color(0.16, 0.55, 0.60),
	"SetSensor": Color(0.48, 0.48, 0.55),
	"SetPhysicsPaused": Color(0.42, 0.42, 0.50),
	"SetDraggable": Color(0.35, 0.55, 0.60),
	"FaceObject": Color(0.55, 0.45, 0.35),
	"SetPivot": Color(0.50, 0.50, 0.42),
	"SetObjectMeta": Color(0.60, 0.50, 0.35),
	"StopAnimation": Color(0.70, 0.33, 0.47),
	"SetCameraPosition": Color(0.30, 0.45, 0.55),
	"CameraFollow": Color(0.28, 0.50, 0.60),
	"TweenPosition": Color(0.45, 0.55, 0.70),
	"TweenScale": Color(0.50, 0.60, 0.65),
	"TweenRotation": Color(0.55, 0.50, 0.70),
	"TweenOpacity": Color(0.45, 0.50, 0.60),
	"StopTween": Color(0.60, 0.40, 0.50),
	"ReadFile": Color(0.35, 0.50, 0.55),
	"WriteFile": Color(0.33, 0.48, 0.52),
	"FileOp": Color(0.40, 0.45, 0.50),
	"HttpRequest": Color(0.30, 0.45, 0.60),
	"CreateInput": Color(0.45, 0.50, 0.62),
	"CreateSlider": Color(0.42, 0.52, 0.60),
	"CreateToggle": Color(0.40, 0.55, 0.58),
	"GetWidgetText": Color(0.38, 0.52, 0.55),
	"SetSliderValue": Color(0.42, 0.50, 0.58),
	"SetToggleState": Color(0.40, 0.53, 0.56),
	"AddTag": Color(0.55, 0.48, 0.40),
	"DeleteByTag": Color(0.65, 0.35, 0.30),
	"SetVisibleByTag": Color(0.45, 0.55, 0.40),
	"SetPositionByTag": Color(0.40, 0.52, 0.45),
	"SetRotationByTag": Color(0.50, 0.50, 0.42),
	"SetOpacityByTag": Color(0.45, 0.52, 0.50),
	"SetScaleByTag": Color(0.48, 0.55, 0.45),
	"ChangeLayerByTag": Color(0.42, 0.48, 0.55),
	"If": Color(0.52, 0.40, 0.55),
	"Repeat": Color(0.45, 0.42, 0.58),
	"CreateGroup": Color(0.35, 0.45, 0.40),
	"AddToGroup": Color(0.38, 0.50, 0.42),
	"CreateSpriteAnim": Color(0.70, 0.33, 0.47),
	"SetFrame": Color(0.65, 0.40, 0.50),
	"CreateParticles": Color(0.45, 0.40, 0.60),
	"SetParticlesParam": Color(0.48, 0.44, 0.58),
	"DeleteParticles": Color(0.55, 0.35, 0.45),
	"SetGlobalGravity": Color(0.40, 0.42, 0.50),
	"CreateCircle": Color(0.40, 0.60, 0.45),
	"CreateLine": Color(0.45, 0.55, 0.40),
	"SetGradient": Color(0.50, 0.45, 0.65),
	"SetBorder": Color(0.55, 0.50, 0.45),
	"SetParallax": Color(0.35, 0.50, 0.60),
	"SetTableValue": Color(0.42, 0.48, 0.58),
	"GetTableValue": Color(0.40, 0.50, 0.56),
	"InsertArrayValue": Color(0.44, 0.46, 0.56),
	"RemoveArrayValue": Color(0.52, 0.42, 0.48),
	"OverwriteTable": Color(0.46, 0.44, 0.54),
	"ForEachTable": Color(0.40, 0.52, 0.60),
	"LoopRange": Color(0.44, 0.50, 0.62),
	"SetAnchor": Color(0.35, 0.55, 0.65),
}

const CONDITION_COLORS := {
	"Always": Color(0.42, 0.47, 0.30),
	"VariableEquals": Color(0.55, 0.45, 0.22),
	"VariableGreaterThan": Color(0.60, 0.40, 0.20),
	"PayloadEquals": Color(0.35, 0.50, 0.40),
	"PayloadGreaterThan": Color(0.30, 0.55, 0.45),
}

const BUILTIN_EVENTS := [
	"ready", "update", "tap", "input", "timer", "collide", "collide_end",
	"obj_touch_begin", "obj_touch_end", "drag", "back",
	"app_paused", "app_resumed", "var_changed", "widget_changed", "http_done",
]

static func event_name(type: String) -> String:
	var key := "event." + type
	var s := GyroLang.t(key)
	return s if s != key else type


static func action_name(type: String) -> String:
	var key := "action." + type
	var s := GyroLang.t(key)
	return s if s != key else type


static func condition_name(type: String) -> String:
	var key := "condition." + type
	var s := GyroLang.t(key)
	return s if s != key else type


static func palette_sections() -> Array:
	return [
		{"title": GyroLang.t("section.events"), "items": [
			{"kind": "event", "type": "ready", "name": event_name("ready")},
			{"kind": "event", "type": "update", "name": event_name("update")},
			{"kind": "event", "type": "tap", "name": event_name("tap")},
			{"kind": "event", "type": "input", "name": event_name("input")},
			{"kind": "event", "type": "timer", "name": event_name("timer")},
			{"kind": "event", "type": "collide", "name": event_name("collide")},
			{"kind": "event", "type": "custom", "name": GyroLang.t("preset.custom_event")},
			{"kind": "event", "type": "func", "name": GyroLang.t("preset.create_func")},
			{"kind": "event", "type": "obj_touch_begin", "name": event_name("obj_touch_begin")},
			{"kind": "event", "type": "obj_touch_end", "name": event_name("obj_touch_end")},
			{"kind": "event", "type": "drag", "name": event_name("drag")},
			{"kind": "event", "type": "back", "name": event_name("back")},
			{"kind": "event", "type": "app_paused", "name": event_name("app_paused")},
			{"kind": "event", "type": "app_resumed", "name": event_name("app_resumed")},
			{"kind": "event", "type": "var_changed", "name": event_name("var_changed")},
			{"kind": "event", "type": "widget_changed", "name": event_name("widget_changed")},
			{"kind": "event", "type": "http_done", "name": event_name("http_done")},
			{"kind": "event", "type": "collide_end", "name": event_name("collide_end")},
		]},
		{"title": GyroLang.t("section.objects"), "items": [
			{"kind": "action", "type": "CreateObject", "name": GyroLang.t("preset.create_object"), "preset": {"type": "rect"}},
			{"kind": "action", "type": "CreateObject", "name": GyroLang.t("preset.create_object"), "preset": {"type": "label"}},
			{"kind": "action", "type": "CreateObject", "name": GyroLang.t("palette.create_sprite"), "preset": {"type": "sprite"}},
			{"kind": "action", "type": "SetSize", "name": action_name("SetSize")},
			{"kind": "action", "type": "MoveNode", "name": action_name("MoveNode")},
			{"kind": "action", "type": "SetNodeProperty", "name": action_name("SetNodeProperty")},
			{"kind": "action", "type": "SetText", "name": action_name("SetText")},
			{"kind": "action", "type": "PlayAnimation", "name": action_name("PlayAnimation")},
			{"kind": "action", "type": "SetSolid", "name": action_name("SetSolid")},
			{"kind": "action", "type": "DeleteObject", "name": action_name("DeleteObject")},
			{"kind": "action", "type": "AddVelocity", "name": GyroLang.t("preset.jump"), "preset": {"y": -700}},
			{"kind": "action", "type": "SetVisible", "name": action_name("SetVisible")},
			{"kind": "action", "type": "SetOpacity", "name": action_name("SetOpacity")},
			{"kind": "action", "type": "SetRotation", "name": action_name("SetRotation")},
			{"kind": "action", "type": "SetScale", "name": action_name("SetScale")},
			{"kind": "action", "type": "ChangeLayer", "name": action_name("ChangeLayer")},
			{"kind": "action", "type": "SetTexture", "name": action_name("SetTexture")},
			{"kind": "action", "type": "SetCornerRadius", "name": action_name("SetCornerRadius")},
			{"kind": "action", "type": "SetFontSize", "name": action_name("SetFontSize")},
			{"kind": "action", "type": "SetColor", "name": action_name("SetColor")},
			{"kind": "action", "type": "SetTextAlign", "name": action_name("SetTextAlign")},
			{"kind": "action", "type": "SetSensor", "name": action_name("SetSensor")},
			{"kind": "action", "type": "SetDraggable", "name": action_name("SetDraggable")},
			{"kind": "action", "type": "FaceObject", "name": action_name("FaceObject")},
			{"kind": "action", "type": "SetPivot", "name": action_name("SetPivot")},
			{"kind": "action", "type": "SetObjectMeta", "name": action_name("SetObjectMeta")},
			{"kind": "action", "type": "StopAnimation", "name": action_name("StopAnimation")},
			{"kind": "action", "type": "TweenPosition", "name": action_name("TweenPosition")},
			{"kind": "action", "type": "TweenScale", "name": action_name("TweenScale")},
			{"kind": "action", "type": "TweenRotation", "name": action_name("TweenRotation")},
			{"kind": "action", "type": "TweenOpacity", "name": action_name("TweenOpacity")},
			{"kind": "action", "type": "StopTween", "name": action_name("StopTween")},
			{"kind": "action", "type": "AddTag", "name": action_name("AddTag")},
			{"kind": "action", "type": "DeleteByTag", "name": action_name("DeleteByTag")},
			{"kind": "action", "type": "SetVisibleByTag", "name": action_name("SetVisibleByTag")},
			{"kind": "action", "type": "SetPositionByTag", "name": action_name("SetPositionByTag")},
			{"kind": "action", "type": "SetRotationByTag", "name": action_name("SetRotationByTag")},
			{"kind": "action", "type": "SetOpacityByTag", "name": action_name("SetOpacityByTag")},
			{"kind": "action", "type": "SetScaleByTag", "name": action_name("SetScaleByTag")},
			{"kind": "action", "type": "ChangeLayerByTag", "name": action_name("ChangeLayerByTag")},
			{"kind": "action", "type": "CreateGroup", "name": action_name("CreateGroup")},
			{"kind": "action", "type": "AddToGroup", "name": action_name("AddToGroup")},
			{"kind": "action", "type": "CreateSpriteAnim", "name": action_name("CreateSpriteAnim")},
			{"kind": "action", "type": "SetFrame", "name": action_name("SetFrame")},
			{"kind": "action", "type": "CreateParticles", "name": action_name("CreateParticles")},
			{"kind": "action", "type": "SetParticlesParam", "name": action_name("SetParticlesParam")},
			{"kind": "action", "type": "DeleteParticles", "name": action_name("DeleteParticles")},
			{"kind": "action", "type": "CreateCircle", "name": action_name("CreateCircle")},
			{"kind": "action", "type": "CreateLine", "name": action_name("CreateLine")},
			{"kind": "action", "type": "SetGradient", "name": action_name("SetGradient")},
			{"kind": "action", "type": "SetBorder", "name": action_name("SetBorder")},
			{"kind": "action", "type": "SetParallax", "name": action_name("SetParallax")},
			{"kind": "action", "type": "SetAnchor", "name": action_name("SetAnchor")},
		]},
		{"title": GyroLang.t("variables"), "items": [
			{"kind": "action", "type": "SetVariable", "name": action_name("SetVariable")},
			{"kind": "action", "type": "AddToVariable", "name": action_name("AddToVariable")},
		]},
		{"title": GyroLang.t("section.physics"), "items": [
			{"kind": "action", "type": "SetVelocity", "name": action_name("SetVelocity")},
			{"kind": "action", "type": "AddVelocity", "name": action_name("AddVelocity")},
			{"kind": "action", "type": "SetGravity", "name": action_name("SetGravity")},
		]},
		{"title": GyroLang.t("section.sound"), "items": [
			{"kind": "action", "type": "PlaySound", "name": action_name("PlaySound")},
			{"kind": "action", "type": "StopSound", "name": action_name("StopSound")},
		]},
		{"title": GyroLang.t("section.logic"), "items": [
			{"kind": "action", "type": "Print", "name": action_name("Print")},
			{"kind": "action", "type": "EmitEvent", "name": action_name("EmitEvent")},
			{"kind": "action", "type": "Spawn", "name": action_name("Spawn")},
			{"kind": "action", "type": "StartTimer", "name": action_name("StartTimer")},
			{"kind": "action", "type": "StopTimer", "name": action_name("StopTimer")},
			{"kind": "action", "type": "Wait", "name": action_name("Wait")},
			{"kind": "action", "type": "SaveValue", "name": action_name("SaveValue")},
			{"kind": "action", "type": "LoadValue", "name": action_name("LoadValue")},
			{"kind": "action", "type": "RandomSeed", "name": action_name("RandomSeed")},
			{"kind": "action", "type": "Toast", "name": action_name("Toast")},
			{"kind": "action", "type": "Clipboard", "name": action_name("Clipboard")},
			{"kind": "action", "type": "SetBackgroundColor", "name": action_name("SetBackgroundColor")},
			{"kind": "action", "type": "SetOrientation", "name": action_name("SetOrientation")},
			{"kind": "action", "type": "OpenURL", "name": action_name("OpenURL")},
			{"kind": "action", "type": "SetSoundVolume", "name": action_name("SetSoundVolume")},
			{"kind": "action", "type": "Quit", "name": action_name("Quit")},
			{"kind": "action", "type": "SetPhysicsPaused", "name": action_name("SetPhysicsPaused")},
			{"kind": "action", "type": "SetCameraPosition", "name": action_name("SetCameraPosition")},
			{"kind": "action", "type": "CameraFollow", "name": action_name("CameraFollow")},
			{"kind": "action", "type": "ReadFile", "name": action_name("ReadFile")},
			{"kind": "action", "type": "WriteFile", "name": action_name("WriteFile")},
			{"kind": "action", "type": "FileOp", "name": action_name("FileOp")},
			{"kind": "action", "type": "HttpRequest", "name": action_name("HttpRequest")},
			{"kind": "action", "type": "If", "name": action_name("If")},
			{"kind": "action", "type": "Repeat", "name": action_name("Repeat")},
			{"kind": "action", "type": "SetGlobalGravity", "name": action_name("SetGlobalGravity")},
		]},
		{"title": GyroLang.t("section.tables"), "items": [
			{"kind": "action", "type": "SetTableValue", "name": action_name("SetTableValue")},
			{"kind": "action", "type": "GetTableValue", "name": action_name("GetTableValue")},
			{"kind": "action", "type": "InsertArrayValue", "name": action_name("InsertArrayValue")},
			{"kind": "action", "type": "RemoveArrayValue", "name": action_name("RemoveArrayValue")},
			{"kind": "action", "type": "OverwriteTable", "name": action_name("OverwriteTable")},
			{"kind": "action", "type": "ForEachTable", "name": action_name("ForEachTable")},
			{"kind": "action", "type": "LoopRange", "name": action_name("LoopRange")},
		]},
		{"title": GyroLang.t("section.widgets"), "items": [
			{"kind": "action", "type": "CreateInput", "name": action_name("CreateInput")},
			{"kind": "action", "type": "CreateSlider", "name": action_name("CreateSlider")},
			{"kind": "action", "type": "CreateToggle", "name": action_name("CreateToggle")},
			{"kind": "action", "type": "GetWidgetText", "name": action_name("GetWidgetText")},
			{"kind": "action", "type": "SetSliderValue", "name": action_name("SetSliderValue")},
			{"kind": "action", "type": "SetToggleState", "name": action_name("SetToggleState")},
		]},
		{"title": GyroLang.t("section.conditions"), "items": [
			{"kind": "condition", "type": "Always", "name": condition_name("Always")},
			{"kind": "condition", "type": "VariableEquals", "name": condition_name("VariableEquals")},
			{"kind": "condition", "type": "VariableGreaterThan", "name": condition_name("VariableGreaterThan")},
			{"kind": "condition", "type": "PayloadEquals", "name": condition_name("PayloadEquals")},
			{"kind": "condition", "type": "PayloadGreaterThan", "name": condition_name("PayloadGreaterThan")},
		]},
	]
